baseurl = "https://blog.sonda.red"
title = "SONDARED"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "swapoff"

[params]
  author = "Kalin Daskalov"
  info = "DevOps & Platform Engineer"
  description = "Building with Kubernetes, learning MLOps hands-on"
  keywords = "devops,platform,blog,kubernetes,mlops,intel,ai"
  #avatarurl = "images/avatar.png"
  gravatar = "kalin.daskalov@proton.me"

  #faviconSVG = "/img/favicon.svg"
  favicon_32 = "/images/shebang.png"
  #favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kdaskalov/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/systemscribe/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/daskalovk/"
#[[params.social]]
#  name = "Twitter"
#  icon = "fa fa-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
